#!/bin/bash
cachefile=~/.dmenu-cache
histfile=~/.dmenu-history
HISTSIZE=20

if [ "$1" = "--help" ]; then
	echo "dwm-choose [--clearcache|--clearhistory|--createcache|--help]";
	exit 0
fi

if [ "$1" = "--clearcache" ]; then
	rm "$cachefile"
	exit 0
fi

if [ "$1" = "--clearhistory" ]; then
	rm "$histfile"
	exit 0
fi

# create cache if needed
if [ ! -r "$cachefile" ]; then
	IFS=:
	for dir in $PATH ; do
		cd "$dir" &&
		for file in * ; do
			test -x "$file" && echo "$file"
		done
	done | sort | uniq > "$cachefile"
fi

if [ "$1" = "--createcache" ] ; then
	exit 0;
fi

# run dmenu
if [ "$DMENU_COLORS" ] ; then
    COMMAND=$(cat "$histfile" "$cachefile" | dmenu $DMENU_COLORS)
else
    COMMAND=$(cat "$histfile" "$cachefile" | dmenu)
fi

# prepend COMMAND to history while removing duplicates
# needs bash > v4.0
# this filter is equivalent to:  perl -ne 'print $_ unless $a{$_}++;'
( echo "$COMMAND"; cat "$histfile") | ( declare -A seen; while read -r LINE; do \
    if [[ -n "$LINE" ]] ; then
	    if [[ -z ${seen["$LINE"]} ]] ; then
		echo "$LINE"
		seen["$LINE"]=1
	    fi
	fi
    done ) | head -n $HISTSIZE > "$histfile.new"
mv "$histfile.new" "$histfile"

# run chosen command
exec $COMMAND
