#!/bin/bash
STATUS_SCRIPT=~/.dwm-status
DWM=/usr/local/bin/dwm
DWMCHOOSE=/usr/local/bin/dwm-choose

# refresh cache
${DWMCHOOSE} --clearcache
${DWMCHOOSE} --createcache &

if [ -x "${STATUS_SCRIPT}" ] ; then
    # personalized status script
    (exec "${STATUS_SCRIPT}") &
else
    # default status with time and load
    (while xsetroot -name "$(/bin/date +%H:%M:%S) $(cut -d ' ' -f -3 /proc/loadavg)"; do sleep 2; done) &
fi

exec ${DWM}