#!/bin/bash
STATUS_SCRIPT=~/.dwm-status
DWM=/usr/local/bin/dwm
DWMCHOOSE=/usr/local/bin/dwm-choose

# refresh cache
${DWMCHOOSE} --clearcache
${DWMCHOOSE} --createcache &

if [ -x "${STATUS_SCRIPT}" ] ; then
    # personalized status script
    if [ $(( 0$(stat -c %a "${STATUS_SCRIPT}") & 0022 )) -gt 0 ] ; then
        # sleep is a dirty little workaround because dwm only listens to changes after it has been started
	(sleep 10; xsetroot -name "${STATUS_SCRIPT} is insecure: writeable by group or other") &
    else
	(exec "${STATUS_SCRIPT}") &
    fi
else
    # default status with time and load
    (while xsetroot -name "$(/bin/date +%H:%M:%S) $(cut -d ' ' -f -3 /proc/loadavg)"; do sleep 2; done) &
fi

exec ${DWM}